### ISSUE TITLE
Published package is very large

### ISSUE THREAD

**Issue by kkckkc** [WarnerHooh/babel-plugin-parameter-decorator#13]
The package published to the npm registry is very large, since it includes (in particular) the example/ folder and all associated dependencies for that folder. The overall package is about 97mb. Given I have ~20 components using babel-plugin-parameter-decorator, there is significant overhead.

Can the example/ and test/ folder be removed as part of publishing to NPM

**Comment by WarnerHooh** [comment]
Hey @kkckkc ,

Thanks for your feedback, I will have a quick look and will let you know once I make it.

**Comment by WarnerHooh** [comment]
Hi @kkckkc I have published a new version `1.0.12` which reduced the npm package size. Hope you enjoy it :)

**Comment by kkckkc** [comment]
Very good. Works like a charm
