### ISSUE TITLE
babel-plugin-parameter-decorator not working with create-react-app project and inversify

### ISSUE THREAD

**Issue by albertocorrales** [WarnerHooh/babel-plugin-parameter-decorator#16]
Hi, 

I'm trying to use inversify with a react project generated with create-react-app. The problem is related to using the decorator @inject in the constructor parameters, like in:

```typescript
@injectable()
class Ninja { 
    constructor(
        @inject(KatanaType) private katana: Katana,
        @inject(ShurikenType) private shuriken: Shuriken
    }{}
```

When I execute that code, I have a runtime error: 

> Error: Missing required @Inject or @multiInject annotation in: argument 0 in class Ninja.

I tried to use plugin "babel-plugin-parameter-decorator" to fix that issue, but it doesn't seem to be working.

Here I have a sample project where you can reproduce the issue: https://github.com/albertocorrales/broken-inversify

Thanks

**Comment by alexjneves** [comment]
I finally figured this out after days of bashing my head against the same problem. The issue lies in the plugin not supporting [Parameter Properties](https://www.typescriptlang.org/docs/handbook/classes.html#parameter-properties).

I resolved it by using the traditional approach of declaring a class member explicitly and assigning it in the body of the constructor. In your case:

```javascript
@injectable()
class Ninja { 
    private katana: Katana;
    private shuriken: Shuriken;

    constructor(
        @inject(KatanaType) katana: Katana,
        @inject(ShurikenType) shuriken: Shuriken
    ) {
        this.katana = katana;
        this.shuriken = shuriken;
    }
}
```

It'd be great if this plugin could support parameter properties in the future to save on unnecessary boilerplate.

**Comment by albertocorrales** [comment]
> I finally figured this out after days of bashing my head against the same problem. The issue lies in the plugin not supporting [Parameter Properties](https://www.typescriptlang.org/docs/handbook/classes.html#parameter-properties).
> 
> I resolved it by using the traditional approach of declaring a class member explicitly and assigning it in the body of the constructor. In your case:
> 
> ```js
> @injectable()
> class Ninja { 
>     private katana: Katana;
>     private shuriken: Shuriken;
> 
>     constructor(
>         @inject(KatanaType) katana: Katana,
>         @inject(ShurikenType) shuriken: Shuriken
>     ) {
>         this.katana = katana;
>         this.shuriken = shuriken;
>     }
> }
> ```
> 
> It'd be great if this plugin could support parameter properties in the future to save on unnecessary boilerplate.

Hi @alexjneves, I tried to use the traditional constructor initialization, but using my code sample I'm getting this error:

```js
Failed to compile.

./src/index.tsx 47:17
Module parse failed: Unexpected character '@' (47:17)
You may need an appropriate loader to handle this file type.
| /*#__PURE__*/
| function () {
>   function Ninja(@inject(KatanaType)
|   katana, @inject(ShurikenType)
|   shuriken) {

```
Do you know if I'm missing something?

Thanks,

Alberto.

**Comment by alexjneves** [comment]
Looking at your repo I suspect your problem is that you haven't ejected from CRA, meaning your `.babelrc` will not be used. In that case you have two options: either eject using `npm run eject` or use a tool like [craco](https://github.com/gsoft-inc/craco) to extend CRA's babel config.

**Comment by albertocorrales** [comment]
You are right @alexjneves, if I eject and I configure babel properly, I see it is working fine, even without modifying the constructor parameters. I thought CRA allows you to modify babel without ejecting, but that was actually the problem.

I close this issue as it is working now.

Thanks!!
