### ISSUE TITLE
Babel support for decorators

### ISSUE THREAD

**Issue by ghost** [WarnerHooh/babel-plugin-parameter-decorator#20]
babelrc file
```

{
  "presets": [
    "@babel/preset-env",  
    "@babel/preset-react",  
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@babel/plugin-transform-runtime",
    [
      "@babel/plugin-proposal-decorators",
      {
        "decoratorsBeforeExport": true,
        "legacy": false
      }
    ],
    "@babel/plugin-proposal-class-properties"
  ]
}
```

error 

Failed to compile.

> 
> ./src/api/httpClientFactory.tsx
> Module build failed (from ./node_modules/babel-loader/lib/index.js):
> SyntaxError: ..\httpClientFactory.tsx: Decorators cannot be used to decorate parameters (64:22)
> 
> public constructor(@inject(SERVICE_TYPE.HttpClientStore) httpClientStore: IHttpClientStore) 
>                               ^
>       this._httpClientStore = httpClientStore;
> }
> 

webpack.js
```

 rules: [
      {
        test: /\.(js|jsx|tsx)$/,
        exclude: /node_modules/,
        use: ['babel-loader'],
      },
```

I'm using inversifyjs for dependency resolution. 

Am I missing something ?

**Comment by DanielHGimenez** [comment]
Has anyone found the solution to this problem? I'm with the same problem
