### ISSUE TITLE
Make compatible with Typescript and`reflect-metadata`

### ISSUE THREAD

**Issue by vjpr** [WarnerHooh/babel-plugin-parameter-decorator#4]
Decorator-based libraries like https://github.com/typestack/routing-controllers make use of Typescript type metadata like so:

```
var format = Reflect.getMetadata("design:paramtypes", object, methodName)[index];
```

In Typescript, when enabling the `emitDecoratorMetadata` option, design-time type metadata is added to elements using special keys such as `design:paramtypes`, `design:type`, `design:returntype`. More explained here: http://blog.wolksoftware.com/decorators-metadata-reflection-in-typescript-from-novice-to-expert-part-4

Could we add this metadata using this plugin?

**Comment by WarnerHooh** [comment]
Hi @vjpr,

Yes, we can, and I am managing to implement this `controller` like service lib (based on this plugin), then we are able to work with the request in declarative way. The reflect-metadata is just another topic, which we store the metadata, and this plugin aims to provide this metadata.

So the declarative service looks like:
``` javascript
class ArticleService extends HttpClient {
  @GET('/article/:id')
  fetchArticle(@Path('id') id) {
  }
}
```
