### ISSUE TITLE
Decorators are assumed to have a return value

### ISSUE THREAD

**Issue by VincentBailly** [WarnerHooh/babel-plugin-parameter-decorator#7]
This plugin adds the following code to the output, which does not support the decorator returning nothing. Typescript supports this.

```
  Foo = MyDecorator()(Foo, undefined, 0);
```

expected:
```
  Foo = MyDecorator()(Foo, undefined, 0) || Foo;
```

**Comment by WarnerHooh** [comment]
Thanks @VincentBailly for your feedback and contribution, merged your commit in the new version.

**Comment by VincentBailly** [comment]
Thanks a lot @WarnerHooh for the quick merging and publishing, very much appreciated.
